title: Jaeyeon Jeong's Homepage
page-top-title: Jaeyeon Jeong
top-section-bg-text: Jaeyeon Jeong
home-subtitle: Jaeyeon Jeong | Janice
copyright-text: '&copy; Jaeyeon Jeong 2025. All Rights Reserved.'
